[build-system]
requires = ["setuptools>=84", "wheel>=0.48"]
build-backend = "setuptools.build_meta"

[project]
name = "matrix-directory-backend"
version = "0.1.0"
authors = [
    { name = "Chris Dedman" },
    { name = "Simon Roy" }
]
maintainers = [
    { name = "Code Society Lab", email = "admin@codesociety.xyz" }
]
description = "Backend for the Matrix Directory"
readme = { text = "Backend for the Matrix Directory.", content-type = "text/markdown" }
license = "MIT"
requires-python = ">=3.10"

dependencies = [
  "fastapi[standard]>=0.141.1",
  "sqlmodel>=0.0.38",
  "sqlmodel-toolkit @ git+https://github.com/Code-Society-Lab/sqlmodel-toolkit.git",
  "pelican-migration>=0.1.3a0",
  "psycopg[binary]>=3.3.4",
  "pydantic-settings>=2.15.0",
  "httpx>=0.28.1",
  "authlib>=1.7.2",
  "itsdangerous>=2.2.0",
]

[project.optional-dependencies]
dev = [
  "black==26.5.1",
  "pytest==9.1.1",
  "mypy==2.3.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
