"""20260822004458 - Require every profile to have a Matrix ID.

Generated by pelican autogenerate. Review before applying.
"""

from pelican import change_table, migration


@migration.up
def upgrade() -> None:
    with change_table("profiles") as table:
        table.alter("matrix_id", nullable=False)


@migration.down
def downgrade() -> None:
    with change_table("profiles") as table:
        table.alter("matrix_id", nullable=True)
